version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: vprodcointainers/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MY_SQL_ROOT_PASSWORD=vproddbpass

  vprodcache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - rabbitmq.username=guest
      - rabbitmq.password=guest
  
  vproapp:
    build:
      context: ./Docker-files/app
    image: vprodcointainers/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  vproweb:
    build:
      context: ./Docker-files/web
    image: vprodcointainers/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}     
